// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1768999421665

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0xD5EBEA28, 0x3D3CE319, 0xC41EDBC9 };