// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769071883714

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0xCFF64FCE, 0x1944F3AA, 0xD56A225 };