// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1770354316284

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 2;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0x40B9E2A8, 0xA8246FC7 };